FROM python:3.11-slim
WORKDIR /app
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn
COPY backend/ .
EXPOSE 5000
CMD ["gunicorn", "src.app:app", \
     "--bind", "0.0.0.0:5000", \
     "--timeout", "600", \
     "-k", "gevent", \
     "--workers", "1", \
     "--log-level", "info"]